using System.Globalization;
using System.Text;

namespace CodeReviewDaemon.Sample.Agents.DeveloperLearnings;

/// <summary>
/// Renders the four view files from a <see cref="DeveloperLearningsView"/>.
/// <para>
/// <b>Pure formatters.</b> Nothing here counts, filters by a threshold, or decides a state — every number
/// and every bucket arrives already computed. That separation is what lets these files be regenerated to
/// resolve a conflict rather than merged: a view is a projection, so re-rendering always converges, and it
/// only converges if rendering is a function of the ledger and nothing else.
/// </para>
/// <para>
/// <b>Line endings are <c>\n</c>, explicitly, not <c>Environment.NewLine</c>.</b> These files are committed
/// and diffed; taking the platform's newline would make the same ledger produce a different file on a
/// different host, and every rendered-file diff would then be noise.
/// </para>
/// <para>
/// <b>Every number is formatted with <see cref="CultureInfo.InvariantCulture"/>.</b> A decimal comma in a
/// committed file is a diff on every machine that renders it next.
/// </para>
/// </summary>
internal static class DeveloperLearningsRenderer
{
    /// <summary>Line separator for every rendered file. Fixed, not the platform's.</summary>
    private const string Nl = "\n";

    /// <summary>Most patterns the checklist carries. The spec's cap; the floor is whatever exists.</summary>
    public const int MaxChecklistPatterns = 5;

    private const string Banner =
        "<!-- Generated by the code review daemon. This file is re-rendered from the observation ledger on "
        + "every run; hand edits are overwritten. -->";

    /// <summary>
    /// The file a person reads. Every section is always present; an empty one says it is empty, because a
    /// missing section and an empty one are different facts and only one of them is a bug.
    /// </summary>
    /// <param name="view">The developer's projected ledger.</param>
    public static string RenderProfile(DeveloperLearningsView view)
    {
        ArgumentNullException.ThrowIfNull(view);

        var sb = new StringBuilder();
        _ = sb.Append(Banner).Append(Nl).Append(Nl);
        _ = sb.Append("# Developer learnings — ").Append(view.DeveloperSlug).Append(Nl).Append(Nl);
        _ = sb.Append("Rendered ")
            .Append(view.GeneratedAtUtc)
            .Append(" from ")
            .Append(Count(view.Observations, "observation file"))
            .Append('.')
            .Append(Nl)
            .Append(Nl);

        AppendSnapshot(sb, view);
        AppendRegressions(sb, view);
        AppendActive(sb, view);
        AppendStateSummary(sb, "Watch", view.Watch, "No patterns are on watch.", view);
        AppendResolved(sb, view);
        AppendStateSummary(sb, "Unjudgeable", view.Unjudgeable, "No patterns are unjudgeable.", view);
        AppendProvenance(sb, view);

        return sb.ToString();
    }

    /// <summary>
    /// The archive view: what resolved, what came back, and what there was never enough exposure to judge.
    /// <para>
    /// Section 2 is this system's check on itself. A high regression rate means <c>ResolutionConfidence</c>
    /// is set too loose, and that is only visible if resolutions and their returns are rendered together.
    /// </para>
    /// </summary>
    /// <param name="view">The developer's projected ledger.</param>
    public static string RenderProgress(DeveloperLearningsView view)
    {
        ArgumentNullException.ThrowIfNull(view);

        var sb = new StringBuilder();
        _ = sb.Append(Banner).Append(Nl).Append(Nl);
        _ = sb.Append("# Progress — ").Append(view.DeveloperSlug).Append(Nl).Append(Nl);
        _ = sb.Append("Rendered ")
            .Append(view.GeneratedAtUtc)
            .Append(" from ")
            .Append(Count(view.Observations, "observation file"))
            .Append('.')
            .Append(Nl)
            .Append(Nl);

        _ = sb.Append("## 1. Resolved").Append(Nl).Append(Nl);
        if (view.Resolved.Count == 0)
        {
            AppendEmpty(sb, "No pattern has resolved yet.");
        }
        else
        {
            _ = sb.Append(
                    "Clean streak counts EXPOSED PRs — PRs where this pattern's specialist ran and completed "
                        + "— never calendar days and never all PRs."
                )
                .Append(Nl)
                .Append(Nl);
            _ = sb.Append("| Pattern | Occurrences | Active period | Clean streak | Confidence | Provisional |")
                .Append(Nl)
                .Append("| --- | --- | --- | --- | --- | --- |")
                .Append(Nl);
            foreach (var pattern in view.Resolved)
            {
                var standing = pattern.Standing;
                _ = sb.Append("| ")
                    .Append(Cell(standing.PatternId))
                    .Append(" | ")
                    .Append(Occurrences(standing))
                    .Append(" | ")
                    .Append(Day(standing.FirstSeenUtc))
                    .Append(" → ")
                    .Append(Day(standing.LastSeenUtc))
                    .Append(" | ")
                    .Append(standing.CleanStreak.ToString(CultureInfo.InvariantCulture))
                    .Append(" exposed PRs | ")
                    .Append(Percent(1.0 - standing.LuckProbability))
                    .Append(" | ")
                    .Append(standing.Provisional ? "yes — cohort drop in this dimension" : "no")
                    .Append(" |")
                    .Append(Nl);
            }

            _ = sb.Append(Nl);
            if (view.ProvisionalResolutions.Count > 0)
            {
                _ = sb.Append("Provisional resolutions are excluded from the headline resolved count: the ")
                    .Append("population-wide finding rate for their dimension fell this window, so an ")
                    .Append("apparent improvement is not attributable to this developer.")
                    .Append(Nl)
                    .Append(Nl);
            }
        }

        _ = sb.Append("## 2. Regressed after resolution").Append(Nl).Append(Nl);
        if (view.Regressions.Count == 0)
        {
            AppendEmpty(sb, "No resolved pattern has come back.");
        }
        else
        {
            _ = sb.Append("| Pattern | Occurrences | Returned | Clean streak broken | Last seen |")
                .Append(Nl)
                .Append("| --- | --- | --- | --- | --- |")
                .Append(Nl);
            foreach (var pattern in view.Regressions)
            {
                var standing = pattern.Standing;
                _ = sb.Append("| ")
                    .Append(Cell(standing.PatternId))
                    .Append(" | ")
                    .Append(Occurrences(standing))
                    .Append(" | ")
                    .Append(standing.RegressedAtUtc is null ? "—" : Day(standing.RegressedAtUtc))
                    .Append(" | ")
                    .Append(
                        standing.StreakBrokenAt is null
                            ? "—"
                            : standing.StreakBrokenAt.Value.ToString(CultureInfo.InvariantCulture) + " exposed PRs"
                    )
                    .Append(" | ")
                    .Append(Day(standing.LastSeenUtc))
                    .Append(" |")
                    .Append(Nl);
            }

            _ = sb.Append(Nl)
                .Append("A returning pattern keeps its whole count; it is never reset to 1. If this section ")
                .Append("is busy, ResolutionConfidence is set too loose.")
                .Append(Nl)
                .Append(Nl);
        }

        _ = sb.Append("## 3. Trend — findings per exposed PR, by dimension").Append(Nl).Append(Nl);
        if (view.DimensionTrends.Count == 0)
        {
            AppendEmpty(sb, "No specialist has completed on any of this developer's PRs.");
        }
        else
        {
            _ = sb.Append("Windows of ")
                .Append(view.Thresholds.ActiveWindowPrs.ToString(CultureInfo.InvariantCulture))
                .Append(" exposed PRs, oldest first, at most ")
                .Append(DeveloperLearningsView.ProgressTrendWindows.ToString(CultureInfo.InvariantCulture))
                .Append(". Findings count every pattern, so this can exceed 1.0 — it is a count per PR, not ")
                .Append("the bounded per-pattern probability used elsewhere in these files.")
                .Append(Nl)
                .Append(Nl);
            foreach (var trend in view.DimensionTrends)
            {
                _ = sb.Append("**").Append(trend.Dimension).Append("**").Append(Nl).Append(Nl);
                if (trend.Windows.Count == 0)
                {
                    AppendEmpty(sb, "Never exposed.");
                    continue;
                }

                _ = sb.Append("| Window | Exposed PRs | Findings | Findings per exposed PR |")
                    .Append(Nl)
                    .Append("| --- | --- | --- | --- |")
                    .Append(Nl);
                for (var i = 0; i < trend.Windows.Count; i++)
                {
                    var window = trend.Windows[i];
                    _ = sb.Append("| ")
                        .Append((i + 1).ToString(CultureInfo.InvariantCulture))
                        .Append(window.Partial ? " (partial) | " : " | ")
                        .Append(window.ExposedPrs.ToString(CultureInfo.InvariantCulture))
                        .Append(" | ")
                        .Append(window.Findings.ToString(CultureInfo.InvariantCulture))
                        .Append(" | ")
                        .Append(Num(window.FindingsPerExposedPr))
                        .Append(" |")
                        .Append(Nl);
                }

                _ = sb.Append(Nl);
            }
        }

        _ = sb.Append("## 4. Not enough exposure to judge").Append(Nl).Append(Nl);
        if (view.Unjudgeable.Count == 0)
        {
            AppendEmpty(sb, "Every pattern has enough exposure to judge.");
        }
        else
        {
            _ = sb.Append(
                    "Not progress. A developer who stopped writing this kind of code has not improved, and "
                        + "neither has one whose reviewer stopped looking."
                )
                .Append(Nl)
                .Append(Nl);
            AppendPatternList(sb, view.Unjudgeable);
        }

        return sb.ToString();
    }

    /// <summary>
    /// The short file, built to be injected wholesale into a coding agent later. Title and the single
    /// "how to avoid it" line, nothing else.
    /// <para>
    /// Prose is collapsed to one physical line per pattern, which is what bounds the file's length: a
    /// multi-paragraph body from the model would otherwise carry its own newlines straight through and the
    /// under-40-lines property would depend on the model's formatting rather than on this code.
    /// </para>
    /// </summary>
    /// <param name="view">The developer's projected ledger.</param>
    public static string RenderChecklist(DeveloperLearningsView view)
    {
        ArgumentNullException.ThrowIfNull(view);

        var ranked = view
            .Active.OrderByDescending(DeveloperLearningsView.ChecklistScore)
            .ThenBy(p => p.Standing.PatternId, StringComparer.Ordinal)
            .Take(MaxChecklistPatterns)
            .ToArray();

        var sb = new StringBuilder();
        _ = sb.Append(Banner).Append(Nl).Append(Nl);
        _ = sb.Append("# Review checklist — ").Append(view.DeveloperSlug).Append(Nl).Append(Nl);
        _ = sb.Append("Rendered ").Append(view.GeneratedAtUtc).Append('.').Append(Nl).Append(Nl);

        if (ranked.Length == 0)
        {
            AppendEmpty(sb, "No active patterns. There is nothing to watch for on this developer's PRs.");
            return sb.ToString();
        }

        _ = sb.Append("Top ")
            .Append(ranked.Length.ToString(CultureInfo.InvariantCulture))
            .Append(" of ")
            .Append(Count(view.Active.Count, "active pattern"))
            .Append(", ranked by rate ÷ (1 + clean streak in exposed PRs).")
            .Append(Nl)
            .Append(Nl);

        foreach (var pattern in ranked)
        {
            _ = sb.Append("- **")
                .Append(OneLine(pattern.Prose.Title))
                .Append("** — ")
                .Append(OneLine(pattern.Prose.HowToAvoid))
                .Append(Nl);
        }

        return sb.ToString();
    }

    /// <summary>
    /// The roster across developers.
    /// <para>
    /// <b>Sorted by last activity, never by pattern count.</b> Ordering by "worst" turns a feedback tool
    /// into a leaderboard, which changes how everyone treats the whole system. Ties break on the slug so the
    /// file is a deterministic function of its input — two developers' PRs closing at once must regenerate
    /// to the same bytes whichever order they are handed in.
    /// </para>
    /// </summary>
    /// <param name="views">One projected view per developer, in any order.</param>
    /// <param name="generatedAtUtc">Render time for the banner.</param>
    public static string RenderIndex(IReadOnlyList<DeveloperLearningsView> views, DateTimeOffset generatedAtUtc)
    {
        ArgumentNullException.ThrowIfNull(views);

        var sb = new StringBuilder();
        _ = sb.Append(Banner).Append(Nl).Append(Nl);
        _ = sb.Append("# Developer learnings").Append(Nl).Append(Nl);
        _ = sb.Append("Rendered ")
            .Append(DeveloperLearningsView.Iso(generatedAtUtc))
            .Append(" across ")
            .Append(Count(views.Count, "developer"))
            .Append('.')
            .Append(Nl)
            .Append(Nl);

        if (views.Count == 0)
        {
            AppendEmpty(sb, "No developer has an observation ledger yet.");
            return sb.ToString();
        }

        _ = sb.Append(
                "Sorted by last activity, not by pattern count — this is not a leaderboard. Counts are "
                    + "patterns, and every pattern's rate is measured in exposed PRs."
            )
            .Append(Nl)
            .Append(Nl);
        _ = sb.Append("| Developer | PRs reviewed | Active | Resolved | Regressed | Last activity |")
            .Append(Nl)
            .Append("| --- | --- | --- | --- | --- | --- |")
            .Append(Nl);

        var ordered = views
            .OrderByDescending(v =>
                v.LastObservedUtc is null
                    ? DateTimeOffset.MinValue
                    : DeveloperLearningsLedger.ParseTimestamp(v.LastObservedUtc)
            )
            .ThenBy(v => v.DeveloperSlug, StringComparer.Ordinal);

        var provisional = 0;
        foreach (var view in ordered)
        {
            provisional += view.ProvisionalResolutions.Count;
            _ = sb.Append("| ")
                .Append(Cell(view.DeveloperSlug))
                .Append(" | ")
                .Append(view.Observations.ToString(CultureInfo.InvariantCulture))
                .Append(" | ")
                .Append(view.Active.Count.ToString(CultureInfo.InvariantCulture))
                .Append(" | ")
                .Append(view.ConfirmedResolvedCount.ToString(CultureInfo.InvariantCulture))
                .Append(" | ")
                .Append(view.Regressions.Count.ToString(CultureInfo.InvariantCulture))
                .Append(" | ")
                .Append(view.LastObservedUtc is null ? "never" : Day(view.LastObservedUtc))
                .Append(" |")
                .Append(Nl);
        }

        _ = sb.Append(Nl);
        _ = sb.Append("Resolved counts CONFIRMED resolutions only. ")
            .Append(
                provisional == 0
                    ? "No resolution is currently provisional."
                    : Count(provisional, "resolution")
                        + " held provisional pending a window without a cohort-wide drop; see each "
                        + "developer's progress.md."
            )
            .Append(Nl);

        return sb.ToString();
    }

    private static void AppendSnapshot(StringBuilder sb, DeveloperLearningsView view)
    {
        _ = sb.Append("## Snapshot").Append(Nl).Append(Nl);
        _ = sb.Append("| Fact | Value |").Append(Nl).Append("| --- | --- |").Append(Nl);
        Row(sb, "Identity", "`" + view.DeveloperSlug + "`");
        Row(
            sb,
            "PRs reviewed",
            view.Observations.ToString(CultureInfo.InvariantCulture)
                + " — one observation file is written per closed PR, so this is the observation count under "
                + "another name, not a second measurement of it"
        );
        Row(sb, "Distinct patterns", view.Patterns.Count.ToString(CultureInfo.InvariantCulture));
        Row(sb, "Active", view.Active.Count.ToString(CultureInfo.InvariantCulture));
        Row(sb, "Watch", view.Watch.Count.ToString(CultureInfo.InvariantCulture));
        Row(sb, "Resolved (confirmed)", view.ConfirmedResolvedCount.ToString(CultureInfo.InvariantCulture));
        Row(sb, "Resolved (provisional)", view.ProvisionalResolutions.Count.ToString(CultureInfo.InvariantCulture));
        Row(sb, "Unjudgeable", view.Unjudgeable.Count.ToString(CultureInfo.InvariantCulture));
        Row(
            sb,
            "Regressed",
            view.Regressions.Count.ToString(CultureInfo.InvariantCulture)
                + " — a flag, not a state; these are also counted in their state row above"
        );
        Row(sb, "First observed", view.FirstObservedUtc is null ? "never" : Day(view.FirstObservedUtc));
        Row(sb, "Last observed", view.LastObservedUtc is null ? "never" : Day(view.LastObservedUtc));
        _ = sb.Append(Nl);
    }

    private static void AppendRegressions(StringBuilder sb, DeveloperLearningsView view)
    {
        _ = sb.Append("## Regressions").Append(Nl).Append(Nl);
        if (view.Regressions.Count == 0)
        {
            AppendEmpty(sb, "No pattern has come back after resolving.");
            return;
        }

        _ = sb.Append(
                "First, because it is the most actionable thing here. A returning pattern keeps its whole "
                    + "history; these also appear in their state section below."
            )
            .Append(Nl)
            .Append(Nl);
        foreach (var pattern in view.Regressions)
        {
            var standing = pattern.Standing;
            _ = sb.Append("- **")
                .Append(OneLine(pattern.Prose.Title))
                .Append("** (`")
                .Append(standing.PatternId)
                .Append("`) — returned ")
                .Append(standing.RegressedAtUtc is null ? "at an unrecorded time" : Day(standing.RegressedAtUtc))
                .Append(", breaking a clean streak of ")
                .Append(
                    standing.StreakBrokenAt is null
                        ? "an unrecorded number of"
                        : standing.StreakBrokenAt.Value.ToString(CultureInfo.InvariantCulture)
                )
                .Append(" exposed PRs. Now ")
                .Append(standing.Occurrences.ToString(CultureInfo.InvariantCulture))
                .Append(" occurrences in total.")
                .Append(Nl);
        }

        _ = sb.Append(Nl);
    }

    private static void AppendActive(StringBuilder sb, DeveloperLearningsView view)
    {
        _ = sb.Append("## Active patterns").Append(Nl).Append(Nl);
        if (view.Active.Count == 0)
        {
            AppendEmpty(sb, "No active patterns.");
            return;
        }

        _ = sb.Append("Rate is Laplace-smoothed occurrences per EXPOSED PR — `(hits + 1) / (exposed + 2)` — ")
            .Append("over the pattern's own window from first hit to last hit inclusive. Trend compares the ")
            .Append("last ")
            .Append(view.Thresholds.ActiveWindowPrs.ToString(CultureInfo.InvariantCulture))
            .Append(" exposed PRs with the ")
            .Append(view.Thresholds.ActiveWindowPrs.ToString(CultureInfo.InvariantCulture))
            .Append(" before them, and reports nothing unless both hold at least ")
            .Append(Math.Max(1, view.Thresholds.ActiveWindowPrs / 2).ToString(CultureInfo.InvariantCulture))
            .Append('.')
            .Append(Nl)
            .Append(Nl);

        _ = sb.Append("| Pattern | Occurrences | Rate | First | Last | Clean streak | Trend |")
            .Append(Nl)
            .Append("| --- | --- | --- | --- | --- | --- | --- |")
            .Append(Nl);
        foreach (var pattern in view.Active)
        {
            var standing = pattern.Standing;
            _ = sb.Append("| ")
                .Append(Cell(standing.PatternId))
                .Append(" | ")
                .Append(Occurrences(standing))
                .Append(" | ")
                .Append(Num(standing.Rate))
                .Append(" | ")
                .Append(Day(standing.FirstSeenUtc))
                .Append(" | ")
                .Append(Day(standing.LastSeenUtc))
                .Append(" | ")
                .Append(standing.CleanStreak.ToString(CultureInfo.InvariantCulture))
                .Append(" exposed PRs | ")
                .Append(Trend(pattern.Trend))
                .Append(" |")
                .Append(Nl);
        }

        _ = sb.Append(Nl);

        foreach (var pattern in view.Active)
        {
            _ = sb.Append("### ").Append(OneLine(pattern.Prose.Title)).Append(Nl).Append(Nl);
            _ = sb.Append("`")
                .Append(pattern.Standing.PatternId)
                .Append("` · ")
                .Append(pattern.Standing.Dimension)
                .Append(Nl)
                .Append(Nl);
            _ = sb.Append("**What it is** — ").Append(OneLine(pattern.Prose.WhatItIs)).Append(Nl).Append(Nl);
            _ = sb.Append("**Why it matters** — ").Append(OneLine(pattern.Prose.WhyItMatters)).Append(Nl).Append(Nl);
            _ = sb.Append("**How to avoid it** — ").Append(OneLine(pattern.Prose.HowToAvoid)).Append(Nl).Append(Nl);
            _ = sb.Append("**Seen in**").Append(Nl).Append(Nl);
            if (pattern.Sightings.Count == 0)
            {
                AppendEmpty(sb, "No PR references recorded.");
                continue;
            }

            foreach (var sighting in pattern.Sightings)
            {
                _ = sb.Append("- ")
                    .Append(Day(sighting.ObservedAtUtc))
                    .Append(" · `")
                    .Append(sighting.SourcePr)
                    .Append("` · ")
                    .Append(sighting.Severity)
                    .Append(" · ")
                    .Append(sighting.Location)
                    .Append(Nl);
            }

            _ = sb.Append(Nl);
        }
    }

    private static void AppendResolved(StringBuilder sb, DeveloperLearningsView view)
    {
        _ = sb.Append("## Resolved").Append(Nl).Append(Nl);
        if (view.Resolved.Count == 0)
        {
            AppendEmpty(sb, "No pattern has resolved yet.");
            return;
        }

        _ = sb.Append("Summary only; the detail lives in `progress.md`.").Append(Nl).Append(Nl);
        foreach (var pattern in view.Resolved)
        {
            var standing = pattern.Standing;
            _ = sb.Append("- **")
                .Append(OneLine(pattern.Prose.Title))
                .Append("** — ")
                .Append(Occurrences(standing))
                .Append(", last seen ")
                .Append(Day(standing.LastSeenUtc))
                .Append(", clean for ")
                .Append(standing.CleanStreak.ToString(CultureInfo.InvariantCulture))
                .Append(" exposed PRs (")
                .Append(Percent(1.0 - standing.LuckProbability))
                .Append(" confidence)")
                .Append(standing.Provisional ? " — **provisional**, cohort drop in this dimension" : string.Empty)
                .Append(Nl);
        }

        _ = sb.Append(Nl);
    }

    private static void AppendStateSummary(
        StringBuilder sb,
        string heading,
        IReadOnlyList<PatternView> patterns,
        string emptyText,
        DeveloperLearningsView view
    )
    {
        _ = sb.Append("## ").Append(heading).Append(Nl).Append(Nl);
        if (patterns.Count == 0)
        {
            AppendEmpty(sb, emptyText);
            return;
        }

        if (string.Equals(heading, "Unjudgeable", StringComparison.Ordinal))
        {
            _ = sb.Append("Not progress: no reviewer has exercised these dimensions recently, or too few ")
                .Append("exposed PRs have passed since the last hit. Staleness threshold is ")
                .Append(view.Thresholds.ExposureStalenessDays.ToString(CultureInfo.InvariantCulture))
                .Append(" days.")
                .Append(Nl)
                .Append(Nl);
        }

        AppendPatternList(sb, patterns);
    }

    private static void AppendPatternList(StringBuilder sb, IReadOnlyList<PatternView> patterns)
    {
        foreach (var pattern in patterns)
        {
            var standing = pattern.Standing;
            _ = sb.Append("- **")
                .Append(OneLine(pattern.Prose.Title))
                .Append("** (`")
                .Append(standing.PatternId)
                .Append("`) — ")
                .Append(Occurrences(standing))
                .Append(", last seen ")
                .Append(Day(standing.LastSeenUtc))
                .Append(", clean for ")
                .Append(standing.CleanStreak.ToString(CultureInfo.InvariantCulture))
                .Append(" exposed PRs")
                .Append(Nl);
        }

        _ = sb.Append(Nl);
    }

    private static void AppendProvenance(StringBuilder sb, DeveloperLearningsView view)
    {
        _ = sb.Append("## Provenance").Append(Nl).Append(Nl);
        _ = sb.Append(
                "**Exposure.** A PR counts toward a pattern only where that pattern's specialist ran and "
                    + "reached Completed on it. Every rate, window and clean streak below is measured in exposed "
                    + "PRs — never in calendar days and never in all PRs, both of which would improve when the "
                    + "reviewer got narrower or the developer shipped less."
            )
            .Append(Nl)
            .Append(Nl);
        _ = sb.Append(
                "**What counts as a hit.** Only findings that survived into the shipped review — `kept`, "
                    + "`severity-changed`, `reframed`, `merged-into`. A finding the lead reviewer dropped is not "
                    + "evidence about the author. At most one hit per pattern per PR."
            )
            .Append(Nl)
            .Append(Nl);
        _ = sb.Append(
                "**Who computed what.** Every count, rate, date and state on this page was computed by the "
                    + "daemon from immutable per-PR observation files. The model's only contribution is the "
                    + "pattern prose and the pattern each finding was filed under."
            )
            .Append(Nl)
            .Append(Nl);
        _ = sb.Append("| Threshold | Value |").Append(Nl).Append("| --- | --- |").Append(Nl);
        Row(sb, "ResolutionConfidence", Num(view.Thresholds.ResolutionConfidence));
        Row(sb, "ActiveWindowPrs", view.Thresholds.ActiveWindowPrs.ToString(CultureInfo.InvariantCulture));
        Row(sb, "ExposureStalenessDays", view.Thresholds.ExposureStalenessDays.ToString(CultureInfo.InvariantCulture));
        Row(sb, "CohortDropThreshold", Num(view.Thresholds.CohortDropThreshold));
        _ = sb.Append(Nl);
    }

    private static void Row(StringBuilder sb, string label, string value) =>
        _ = sb.Append("| ").Append(label).Append(" | ").Append(value).Append(" |").Append(Nl);

    private static void AppendEmpty(StringBuilder sb, string text) =>
        _ = sb.Append("_").Append(text).Append("_").Append(Nl).Append(Nl);

    private static string Occurrences(PatternStanding standing) =>
        standing.Occurrences.ToString(CultureInfo.InvariantCulture)
        + " in "
        + standing.ExposedInWindow.ToString(CultureInfo.InvariantCulture)
        + " exposed PRs";

    private static string Trend(PatternTrend trend) =>
        trend.Direction switch
        {
            TrendDirection.InsufficientData => "insufficient data",
            TrendDirection.Improving => "improving (" + Num(trend.PriorRate) + " → " + Num(trend.RecentRate) + ")",
            TrendDirection.Worsening => "worsening (" + Num(trend.PriorRate) + " → " + Num(trend.RecentRate) + ")",
            _ => "unchanged (" + Num(trend.RecentRate) + ")",
        };

    private static string Count(int value, string noun) =>
        value.ToString(CultureInfo.InvariantCulture) + " " + noun + (value == 1 ? string.Empty : "s");

    private static string Num(double? value) =>
        value is null ? "—" : value.Value.ToString("0.00", CultureInfo.InvariantCulture);

    private static string Percent(double value) => (value * 100).ToString("0.0", CultureInfo.InvariantCulture) + "%";

    /// <summary>
    /// Renders a stored ISO timestamp as a date, falling back to the stored text when it cannot be parsed.
    /// An unreadable timestamp is shown as it was written rather than blanked, so the bad file is findable.
    /// </summary>
    private static string Day(string isoUtc)
    {
        var parsed = DeveloperLearningsLedger.ParseTimestamp(isoUtc);
        return parsed == DateTimeOffset.MinValue
            ? isoUtc
            : parsed.ToUniversalTime().ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
    }

    /// <summary>
    /// Collapses model-authored prose to one physical line.
    /// <para>
    /// Load-bearing in two places: it keeps a multi-paragraph body from breaking a markdown table row, and
    /// it is what bounds the checklist's length. Without it, the under-40-lines property would depend on how
    /// the model happened to format its answer.
    /// </para>
    /// </summary>
    private static string OneLine(string text) =>
        string.Join(' ', text.Split((char[]?)null, StringSplitOptions.RemoveEmptyEntries));

    /// <summary>Escapes the one character that would break out of a markdown table cell.</summary>
    private static string Cell(string text) => "`" + text.Replace("|", "\\|", StringComparison.Ordinal) + "`";
}
